### ISSUE TITLE
no visibility of entity or card post integration

### ISSUE THREAD

**Issue by swissMack** [websylv/homeassistant-meteoswiss#13]
versions
Homeassistant  0.110.1
HACS 1.0.1

Followed process installing through HACS , integration is visible as a panel in Configuration/integration, now entities are shown for it
No sensors are shown for it

when adding debug/logging to configuration.yaml errors that respond are that it cannot find reference 

please help

**Comment by swissMack** [comment]
logs:
Log Details (ERROR)
Logger: homeassistant.components.weather
Source: custom_components/meteo-swiss/__init__.py:77 
Integration: Weather (documentation, issues) 
First occurred: 15:39:28 (1 occurrences) 
Last logged: 15:39:28

meteo-swiss: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meteo-swiss/weather.py", line 54, in update
    data = self._client.get_data()
  File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
    return self._client.get_data()
  File "/usr/local/lib/python3.7/site-packages/hamsclient/client.py", line 29, in get_data
    return  {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
