### ISSUE TITLE
station doesn't work

### ISSUE THREAD

**Issue by djax666** [websylv/homeassistant-meteoswiss#2]
Hello,

with these in my configuration.yaml
```yaml
weather:
 - platform: meteo-swiss
   name: "MeteoSwiss" #Will use meteoSwiss as entity name 
   postcode: 1700
   station: GRA
```
I get these error:
```log
2020-02-23 02:37:32 ERROR (MainThread) [homeassistant.components.weather] meteo-swiss: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/config/custom_components/meteo-swiss/weather.py", line 143, in async_update
    self._condition = ms.get_current_condition(self.stationCode)
AttributeError: 'MeteoSwissWeather' object has no attribute 'stationCode'
```

without the station, I get an entity.

Best regards

**Comment by websylv** [comment]
Hello

Thank you for the feedback
I published a new release fixing this issue (0.4.1) it should be available soon in HACS

**Comment by djax666** [comment]
Hello,
I've installed  the 0.4.1 in HACS, added the "station: GRA" in configuration.yaml and restarted,
but I got:

```log
2020-02-23 13:10:43 ERROR (MainThread) [homeassistant.components.weather] meteo-swiss: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/config/custom_components/meteo-swiss/weather.py", line 143, in async_update
    self._condition = ms.get_current_condition(self.stationCode)
AttributeError: 'MeteoSwissWeather' object has no attribute 'stationCode'
```

Best regards

**Comment by djax666** [comment]
OK, I reinstall it and now it works. Update was not enough.
