### ISSUE TITLE
MeteoSwiss stopped working at 18. October 14:30 unexpected

### ISSUE THREAD

**Issue by vistalba** [websylv/homeassistant-meteoswiss#26]
Since 18. October at 14:30 it isn't working anymore.

HA: 0.116.4
Supervisor: 247

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 346, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 471, in async_device_update
    await self.hass.async_add_executor_job(self.update)  # type: ignore
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meteo-swiss/weather.py", line 54, in update
    data = self._client.get_data()
  File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
    return self._client.get_data()
  File "/usr/local/lib/python3.8/site-packages/hamsclient/client.py", line 30, in get_data
    return  {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_condition'
```

**Comment by DreadN** [comment]
What wheather station were you polling?

Mine (Stabio) went down the day after.

**Comment by vistalba** [comment]
@DreadN Using KOP and is working in MeteoSwiss App and Website.

**Comment by websylv** [comment]
it look like MS changed something in the data
i will try to fix asap

**Comment by websylv** [comment]
check with the new version (in HACS) or by hand with this release : https://github.com/websylv/homeassistant-meteoswiss/releases/tag/1.2

**Comment by vistalba** [comment]
For me it is working again but now with two decimals ;) Thanks a lot!
Is there a way to limit/round temperature/humidity decimals to 1?

**Comment by buentead** [comment]
Thanks a lot. It is also working on my side. Great job!

**Comment by DreadN** [comment]
Thanks for your work

Did some troubleshooting.
Cleaned up interface and /custom_component by removing integrations via HA and HACS.
Reinstalled integration and restarted HA.

Created a config for Geneve (GVE) and it's flawless working with 10 entities created.
![image](https://user-images.githubusercontent.com/65244818/96738198-c54ffe00-13be-11eb-9823-121507eb7f5d.png)

While Stabio (SBO) generates errors, and does not create entities.
![image](https://user-images.githubusercontent.com/65244818/96738859-75256b80-13bf-11eb-8941-6a585bb3cf5b.png)

**Comment by BlueMorse** [comment]
Thanks for the quick fix. Just replaced the old Custom files, no reinstall etc. and everything works again - appreciate your work!

**Comment by websylv** [comment]
> Thanks for your work
> 
> Did some troubleshooting.
> Cleaned up interface and /custom_component by removing integrations via HA and HACS.
> Reinstalled integration and restarted HA.
> 
> Created a config for Geneve (GVE) and it's flawless working with 10 entities created.
> ![image](https://user-images.githubusercontent.com/65244818/96738198-c54ffe00-13be-11eb-9823-121507eb7f5d.png)
> 
> While Stabio (SBO) generates errors, and does not create entities.
> ![image](https://user-images.githubusercontent.com/65244818/96738859-75256b80-13bf-11eb-8941-6a585bb3cf5b.png)

I tested to add SBO but for me it look fine 

![image](https://user-images.githubusercontent.com/19144629/97272387-1eda8180-1832-11eb-8b7e-76852e84853d.png)

do you still have the issue ?

**Comment by DreadN** [comment]
> do you still have the issue ?

Yes, unfortunately... :(

Creating a config with SBO returns error in LOGS:
![image](https://user-images.githubusercontent.com/65244818/97363853-7a912300-18a3-11eb-8337-b7e144ddea49.png)

Actually I've created a second set of sensor by creating entities from LUG station but named as "Stabio" to have same entity names and leave my HA automation untouched.

No entity is created if i use SBO directly and errors are logged.
It seems that:

1) the script is not finding the attribute _forecast
```
  File "/usr/local/lib/python3.8/site-packages/hamsclient/client.py", line 32, in get_data
    return  {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast' 
```

2) when trying to update the sensor
```
  File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
    self._data = self._client.get_data()

```  
3) directly in the __init__ script.
```
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
    return self._client.get_data()

```

**Comment by DreadN** [comment]
Gave a try today, and SBO returned online with all entities.
