### ISSUE TITLE
Log Error (Dev Tools)

### ISSUE THREAD

**Issue by shymata** [websylv/homeassistant-meteoswiss#3]
Hello,

Thanks a lot for this app. It's very useful.

So I updated today. HA updated (0.105.5), running on a Pi3B+ (HassOs 3.11).
This message was monitored 8 times this afternoon.
It's working, but...
So if I can help you for anything... ;)

> Log Details (ERROR)
Tue Feb 25 2020 15:26:34 GMT+0100 (heure normale d’Europe centrale)
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 327, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 128, in state_attributes
    if self.temperature is not None:
  File "/config/custom_components/meteo-swiss/weather.py", line 153, in temperature
    return float(self._condition[0]['tre200s0'])
ValueError: could not convert string to float: '-'

>

**Comment by websylv** [comment]
Hello

I noticed the same error message this afernoon
I think it was some wrong data comming from meteo Swiss but not sure i don't log the input data

I added logs to my dev environnement to try to get more informations

**Comment by shymata** [comment]
In fact, no more issue since.
0.106 passed like a charm.

**Comment by websylv** [comment]
no new occurrences  so i close the issue
i really think it was an issue with meteoswiss website
