### ISSUE TITLE
not able to get meteoswiss running

### ISSUE THREAD

**Issue by steuerzentrale** [websylv/homeassistant-meteoswiss#30]
Hi there

this is my first post on github, first of all many thanks for this plugin to get accurate weather data. I am new to the whole smart home thing and learn new things every day. Please excuse that I cant post a debug log, I tried to do so but am really new to the whole lets say programming/scripting thing and have very little knowledge (yet).

As of now I have a Raspberry Pi 4 with hassio 0.118.4 and HACS. I managed to get meteoswiss v 1.2 from HACS and added it via integrations. It shows 10 entities (sensors) for my domicile which is 8953 Dietikon.

However I dont know how to get the data from the meteoswiss integration. I still get the data from the entity weather.home from the integration **Meteorologisk institutt****. I also use the Weather Forecast card where the entity is weather.home but I guess it should be the one from meteoswiss ?

`cards:
      - type: 'custom:weather-card'
        entity: weather.home`

Many thanks 

Kind regards

Andrew

Log from hassio:

Logger: homeassistant.components.sensor
Source: custom_components/meteo-swiss/sensor.py:84
Integration: Sensor (documentation, issues)
First occurred: 19:11:41 (2 occurrences)
Last logged: 19:11:41

    Error adding entities for domain sensor with platform meteo-swiss
    Error while setting up meteo-swiss platform for sensor

Traceback (most recent call last):
  File "/config/custom_components/meteo-swiss/sensor.py", line 82, in state
    return self._data['condition'][0][dataId]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/meteo-swiss/sensor.py", line 84, in state
    _LOGGER.debug("Unable to return data for : %s"%(self._data['condition'][0][dataId]))
IndexError: list index out of range

Logger: homeassistant.components.weather
Source: custom_components/meteo-swiss/weather.py:68
Integration: Weather (documentation, issues)
First occurred: 19:11:41 (2 occurrences)
Last logged: 19:11:41

    Error adding entities for domain weather with platform meteo-swiss
    Error while setting up meteo-swiss platform for weather

Traceback (most recent call last):
  File "/config/custom_components/meteo-swiss/weather.py", line 66, in temperature
    return float(self._condition[0]['tre200s0'])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 144, in state_attributes
    if self.temperature is not None:
  File "/config/custom_components/meteo-swiss/weather.py", line 68, in temperature
    _LOGGER.debug("Error converting temp %s"%self._condition[0]['tre200s0'])
IndexError: list index out of range

**Comment by dalwhin** [comment]
The integration is still not working. I do not know if websylv is still working on this integration. If not he/she should set it to "archived". It's better than let people deal with a non working integration ...

**Comment by bfritscher** [comment]
This integration uses a third-party library to access meteo-swiss data. One of the URL to retrive the list of stations has changes. I fixed the library https://github.com/websylv/hamsclient/pull/1 Until it gets merges you can download https://github.com/bfritscher/hamsclient and copy the hamsclient folder into custom_components\meteo-swiss\ after restarting Home Assistant the integration should work again.

**Comment by dalwhin** [comment]
Thanks for the info. I downloaded the hamsclient from your github link (3 files) and copied it to \meteo-swiss\hamsclient. But there are still errors (after restart and new setup of meteo-swiss). They show up in the log right at the beginning:

- Error adding entities for domain sensor with platform meteo-swiss
- Error while setting up meteo-swiss platform for sensor

And more lines (see first post on top).

**Comment by bfritscher** [comment]
I added it through integrations in the UI choosing meteo swiss.

**Comment by dalwhin** [comment]
Yes I did. I added it in HA integrations. It founds a city near me (Dietikon) and I added it "successfully". I got 10 entities but none of them showes a value. The all showed "nicht verfügbar" (in german). After reboot they showed "wiederhergestellt", but still no values.

**Comment by bfritscher** [comment]
The key thing is the station (three letter key) you chosse at setup. Not
all stations have all the informations. Data is taken from here
https://data.geo.admin.ch/ch.meteoschweiz.messwerte-aktuell/VQHA80.csv and
here
https://data.geo.admin.ch/ch.meteoschweiz.messnetz-automatisch/ch.meteoschweiz.messnetz-automatisch_fr.csv
There is also a weather entity which is created but not listed on the
integration. weather.[cityname] you can use with the weather widget.

**Comment by dalwhin** [comment]
Dietikon has the three letter key DIT as it is in your second link. The integration shows during setup this three letter key. A weather.[cityname] does not show up (no entity in the entities list).

Anyway; I tried it. Thanks for your inputs and help. But as it is not working right now, I will stay for the moment at openweathermap. If websylv is updating the integration in the near future, I will try it again.
