### ISSUE TITLE
Unable to retrieve data

### ISSUE THREAD

**Issue by Vannian** [websylv/homeassistant-meteoswiss#41]
I have this error for the station "Bellinzona"

Traceback (most recent call last):
  File "/config/custom_components/meteo-swiss/sensor.py", line 82, in state
    return self._data['condition'][0][dataId]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 773, in _async_registry_updated
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 453, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 425, in _stringify_state
    state = self.state
  File "/config/custom_components/meteo-swiss/sensor.py", line 84, in state
    _LOGGER.debug("Unable to return data for : %s"%(self._data['condition'][0][dataId]))
IndexError: list index out of range

**Comment by schneich** [comment]
Same issue here. Is there a solution for this error?
