### ISSUE TITLE
No Entity available for "Winterthur / Seen"

### ISSUE THREAD

**Issue by schneich** [websylv/homeassistant-meteoswiss#44]
I spent a couple of nights trying to install this integration. I am able to instal it, but the integration never shows any entities/sensors. The choosen location is "Winterthur/Seen".

![grafik](https://user-images.githubusercontent.com/84641760/131410313-37198a95-dde4-4e3a-8314-c409dfe8ba4b.png)

What am I doing wrong? Or are there no data for Winterthur?

Any help is very much appreciated!
Chris

**Comment by schneich** [comment]
My system is up-to-date:


In the log, I just have seen two errors:
---------------------------------------------------------------------------------------------------------
Logger: homeassistant.components.sensor
Source: custom_components/meteo-swiss/__init__.py:77
Integration: Sensor (documentation, issues)
First occurred: 23:44:01 (12 occurrences)
Last logged: 23:44:02
meteo-swiss: Error on device update!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
    self._data = self._client.get_data()
  File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
    return self._client.get_data()
  File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
    return  {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
---------------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------------
Logger: homeassistant.components.weather
Source: custom_components/meteo-swiss/__init__.py:77
Integration: Weather (documentation, issues)
First occurred: 23:44:01 (1 occurrences)
Last logged: 23:44:01

meteo-swiss: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meteo-swiss/weather.py", line 54, in update
    data = self._client.get_data()
  File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
    return self._client.get_data()
  File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
    return  {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
---------------------------------------------------------------------------------------------------------

**Comment by schneich** [comment]
Ok, I just had a look at the source data. [https://data.geo.admin.ch/](https://github.com/websylv/homeassistant-meteoswiss/issues/30) There are only rain data for Winterthur. But this does not explain, why I can't get the integration running.

**Comment by schneich** [comment]
I just had another look at the logs (debug-mode)

Can anybody help?

`2021-10-02 21:54:18 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration dewpoint which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-02 21:54:18 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration meteo-swiss which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-02 21:54:18 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-02 21:54:43 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2021-10-02 21:54:46 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /supervisor/options request
2021-10-02 21:55:12 DEBUG (MainThread) [custom_components.meteo-swiss] Async setup meteo swiss
2021-10-02 21:55:12 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2021-10-02 21:55:12 WARNING (MainThread) [homeassistant.setup] Setup of input_datetime is taking over 10 seconds.
2021-10-02 21:55:12 WARNING (MainThread) [homeassistant.components.scene] Setup of scene platform homeassistant is taking over 10 seconds.
2021-10-02 21:55:12 WARNING (MainThread) [homeassistant.setup] Setup of system_health is taking over 10 seconds.
2021-10-02 21:55:12 DEBUG (SyncWorker_4) [hamsclient.client] MS Client INIT
2021-10-02 21:55:12 DEBUG (SyncWorker_4) [hamsclient.client] INIT meteoswiss client : name = Winterthur / Seen station = WIN postcode = 8407
2021-10-02 21:55:14 DEBUG (MainThread) [custom_components.meteo-swiss] Current configuration : {'name': 'Winterthur / Seen', 'postcode': 8407, 'station': 'WIN', 'enablesensors': True}
2021-10-02 21:55:14 DEBUG (SyncWorker_4) [custom_components.meteo-swiss] MS Updater update start
2021-10-02 21:55:14 DEBUG (SyncWorker_4) [hamsclient.client] Start update forecast data
2021-10-02 21:55:14 DEBUG (SyncWorker_4) [hamsclient.client] Main URL : https://www.meteosuisse.admin.ch/home/actualite/infos.html?ort=8407&pageIndex=0&tab=search_tab
2021-10-02 21:55:16 DEBUG (SyncWorker_4) [hamsclient.client] Data URL : https://www.meteosuisse.admin.ch/product/output/weather-widget/forecast/version__20211002_1942/fr/840700.json
2021-10-02 21:55:16 ERROR (SyncWorker_4) [custom_components.meteo-swiss] Unexpected error
2021-10-02 21:55:16 DEBUG (SyncWorker_4) [custom_components.meteo-swiss] MS Updater update end
2021-10-02 21:55:17 DEBUG (MainThread) [custom_components.meteo-swiss] Starting entry sensor
2021-10-02 21:55:17 DEBUG (MainThread) [custom_components.meteo-swiss] Start entry weather
2021-10-02 21:55:17 INFO (MainThread) [custom_components.meteo-swiss.sensor] Starting asnyc setup platform
2021-10-02 21:55:17 INFO (MainThread) [custom_components.meteo-swiss.weather] Starting asnyc setup platform
2021-10-02 21:55:18 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
2021-10-02 21:55:18 ERROR (MainThread) [homeassistant.components.weather] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/weather.py", line 54, in update
data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
2021-10-02 21:55:18 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
2021-10-02 21:55:18 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
2021-10-02 21:55:23 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
2021-10-02 21:55:23 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
2021-10-02 21:55:24 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
2021-10-02 21:55:25 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
2021-10-02 21:55:26 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
2021-10-02 21:55:26 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
2021-10-02 21:55:26 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
2021-10-02 21:55:26 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
2021-10-02 21:55:26 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'`

**Comment by schneich** [comment]
Out of fun, I re-installed the integration and set it to Geneva. Everything works fine. All sensor data are there.
So again: it seems as if there are no data available for Winterthur (WIN).
