### ISSUE TITLE
Get forecast by locality name and not by postcode

### ISSUE THREAD

**Issue by serotonie** [websylv/homeassistant-meteoswiss#52]
Hi there,

First of all thanks for the awesome work :)

I just ran into a little issue today.
With the tendency of our beautiful LaPoste Service Public to close more and more little offices in our little villages, we are having more and more localities that have the same postcode than other (in my case, 9 localities for 1 postcode with a height difference of more than 200m between the lower and the highest village).
Because of that, we can have a pretty big difference in the forecast between every locality that have the same postcode.

Would it be feasible to search the location forecast with the locality name and not with the postcode ?

Thanks in Advance

**Comment by mimaret** [comment]
Hello,

I use swiss-meteo(V 1.3) in home assistant. It was working very well. Since a few days, I have an error when updating the info. I uninstalled and reinstalled, to no avail. 

Thanks in Advance

`Logger: homeassistant.components.sensor
Source: custom_components/meteo-swiss/__init__.py:77
Integration: Capteur ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 11:40:56 (12 occurrences)
Last logged: 11:41:08
meteo-swiss: Error on device update!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 737, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
    self._data = self._client.get_data()
  File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
    return self._client.get_data()
  File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
    return  {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'`
