### ISSUE TITLE
Entity not available: weather.xxx 

### ISSUE THREAD

**Issue by muth-zhaw** [websylv/homeassistant-meteoswiss#54]
After an upgrade to Home Assistant 2022.3.x all entities of this integration have become "unavailable".

**Comment by gerdschadler** [comment]
same issue!

**Comment by vistalba** [comment]
Same issue after restart of HA today. Didn‘t updated anything.

**Comment by scottgerring** [comment]
I reckon it's the same problem i'm having - #53 - meteoswiss changed an endpoint

**Comment by LightAngel8366** [comment]
Same issue after restart of HA today. Didn‘t updated anything.

**Comment by scottgerring** [comment]
I posted some hacky patches on #53 that fix the issue, at least for my HA configuration, for anyone that is feeling adventurous.

**Comment by scottgerring** [comment]
> @scottgerring How I can test your hack? Using Supervised installation.

You need to replace hamsclient/client.py and custom_components/meteo-swiss/weather.py with the versions on the two PRs and restart HA. They'll be buried somewhere in your homeassistant install - I run in docker so i'm not sure where for supervisord, but you should be able to use `locate` or so to find them. 

Take backups! And revert back if it doesn't work.

**Comment by LightAngel8366** [comment]
Sorry, I'm not a programmer. I have no idea what to do to get it working again.

**Comment by muth-zhaw** [comment]
I'm feeling stupid right now - can't find a file client.py on my monitored installation. (I have tried eg. `find / -name client.py`)

There is a directory:
`    /config/custom_components/meteo-swiss
`
containing: 
  ` _init__.py     __pycache__     config_flow.py  const.py        manifest.json   sensor.py       translations    weather.py`

Could it be that these files were hidden on purpose or are they maybe renamed?

**Comment by scottgerring** [comment]
> I'm feeling stupid right now - can't find a file client.py on my monitored installation. (I have tried eg. `find / -name client.py`)
> 
> There is a directory: ` /config/custom_components/meteo-swiss` containing: ` _init__.py __pycache__ config_flow.py const.py manifest.json sensor.py translations weather.py`
> 
> Could it be that these files were hidden on purpose or are they maybe renamed?

That's half of it - the other half is for the 'hamsclient' library that homeassistant-meteoswiss depends on. On mine i've got 
```
/config/deps/lib/python3.9/site-packages/hamsclient/client.py
/config/custom_components/meteo-swiss/weather.py
```

**Comment by muth-zhaw** [comment]
> 

on my system `/config/deps ` looks absolutely empty.

I guess this is because of:
 ```
  OS Version:  Home Assistant OS 7.5
  Home Assistant Core: 2022.3.5
```

**Comment by mduelger81** [comment]
Same issue here. Swiss-Meteo Entities not working anymore. Is there any further information or fix?

**Comment by scottgerring** [comment]
> > 
> 
> on my system `/config/deps ` looks absolutely empty.
> 
> I guess this is because of:
> 
> ```
>  OS Version:  Home Assistant OS 7.5
>  Home Assistant Core: 2022.3.5
> ```

Does `hamsclient` exist anywhere in your filesystem? `find / | grep hamsclient`. It's a py package; it might be installed elsewhere, and it might appear as `pyc` only 🤷

**Comment by vistalba** [comment]
In Homeassistant OS the Homeassistant stuff is inside the Homeassistant docker container.

Short:

Replace client.py
```
docker exec -i homeassistant bash
cd /usr/local/lib/python3.9/site-packages/hamsclient/client.py
mv client.py client.py.bak
wget "https://raw.githubusercontent.com/websylv/hamsclient/83367dd76aab590492afe4ff1933ff365e92b8a3/hamsclient/client.py"
exit
```

Replace weather.py:
```
cd /config/custom_components/meteo-swiss/weather.py
mv weather.py weather.py.bak
wget "https://raw.githubusercontent.com/websylv/homeassistant-meteoswiss/a10c9b5da7a8282a197f028e5be1585b6b9535c1/custom_components/meteo-swiss/weather.py"

After that you have to restart homeassistant. Be aware.. this is a WORKAROUND! Hopefully @websylv will update the integration soon.

**Comment by mduelger81** [comment]
Thank you! The Workaround worked for me.

**Comment by scottgerring** [comment]
Hey @vistalba thanks for the write-up and glad it works. I should have time to fix the day shift this evening!

**Comment by vistalba** [comment]
@scottgerring May we have to think about in general again. 
The solution with the new URL with PLZ does just contain the "forecast" for a location with the PLZ. There is no measurement.

The original solution with the specific stations does just show the measurement stations. This leads in different behavior I guess. As until know the real measured temperature was shown.

**Comment by vistalba** [comment]
> Yes, no files named 'hamsclient*' can be found. I think this OS is a sandbox. They are trying to keep it user safe. I will reinstall HA on a standard operating system. I have already spent hours finding workarounds.

Just follow the instructions here ;)
https://github.com/websylv/homeassistant-meteoswiss/issues/54#issuecomment-1074806964

**Comment by scottgerring** [comment]
This fixes the off-by-one in the forecast:
https://raw.githubusercontent.com/scottgerring/homeassistant-meteoswiss/master/custom_components/meteo-swiss/weather.py

@vistalba i'm not sure about the measurement vs forecast thing. This for Thun for instance has a `currentWeather` field on it, but it seems to lag what i'm seeing in  the MS app. Trying to work out what's up. I might just re-use the API from the website for that.

**Comment by vistalba** [comment]
@scottgerring If we want same function as before we have to use whats mentioned here as source: https://github.com/websylv/homeassistant-meteoswiss/issues/54#issuecomment-1074834623

In this case only real measurement stations are available.

**Comment by scottgerring** [comment]
@vistalba yep I take your point. I'm going to park it here for the moment though, as it's close enough to "right" for me, and I don't want to sink time on it if @websylv is going to pick it up again.

If in a week or so if we've not heard back i'll pull both the repos together into one and rejig the whole API bit, and see if we can work out how to publish to HACS. But again I don't want to step on the creators toes, so we'll leave it for them to continue their good work on this extension first :) 

Cheers!

**Comment by badewanne1234** [comment]
Same here - I'm not really fit on Linux, so I tried to locate `client.py` via WinSCP on my Proxmox Instance, where also HA runs in a VM (Home Assisant OS) but no luck..
There are a few `client.py` files, but none of them contains the MeteoSuisse stuff I can see in [https://raw.githubusercontent.com/websylv/hamsclient/83367dd76aab590492afe4ff1933ff365e92b8a3/hamsclient/client.py](url)

Would appreciate if someone could point me to the right direction :)

![grafik](https://user-images.githubusercontent.com/82471417/159683693-2d577d18-fb93-4043-a015-ea161964ba37.png)

**Comment by scottgerring** [comment]
@vistalba I had a bit more of a look. As far as I can see, the 'currentWeather' value that's set in the new URL isn't used anywhere, _except_ the `icon`, which is used to control the UI icon. Aside from that the data picked out is the forecast object.

The actual current temperature/humidity/pressure/etc. are all taken from [this csv](https://data.geo.admin.ch/ch.meteoschweiz.messwerte-aktuell/VQHA80.csv) which we haven't changed.

**Comment by giopons** [comment]
Hi, on my side the integration suddenly stopped working as well. no more sensors detected even though I did not change anything. I removed the integration, then redownloaded it. select the station.... nothing. no sensors. I even tried to take Geneva/cointrin..... 

there error Is see in the log 

meteo-swiss: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 737, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meteo-swiss/weather.py", line 54, in update
    data = self._client.get_data()
  File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
    return self._client.get_data()
  File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
    return  {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'


any help is welcome ;-)
thanks

**Comment by Brun059** [comment]
and I get an "invalid add-on repository" when adding this URL to HA's add-ons. (using HA-blue, the version for dummies)

**Comment by giopons** [comment]
@scottgerring thanks! I am not familiar with the shell but I might give it a try ,-)

**Comment by Brun059** [comment]
@scottgerring , Thanks. I use HA blue, the pre-installed version for dummies - and am absolutely useless when it comes about installations. I guess I wait till it gets released.

**Comment by inch1957** [comment]
Thanks, followed the guide and now it’s back to work. Great job hope they fix it officially too!

**Comment by scottgerring** [comment]
I've managed to install it using a HACS manual repository from my own fork. This should work without hacking away at the console and can be done just from the HA web interface:

0. Remove your old meteo-swiss installation from HACS
1. From the HACS integrations screen, click the "..." in the top right corner and select "Custom Repositories"
2. Add `https://github.com/scottgerring/homeassistant-meteoswiss`
3. Click on the meteoswiss integration that appears, and configure normally. When you are prompted for a version, select 1.4. 

It's got the same name as this one in the HACS UI, but you can tell that it's the version that you've published as the authors will include me as well as the original author.

**Comment by giopons** [comment]
Awesome!! Thank you @scottgerring . Really appreciate your help. Works well

**Comment by samira734MO** [comment]
Perfect! Many thanks to @scottering and the others who helped to find a solution. The HACS guide (above) without console hackery worked perfectly. The weather data are back. HassOS core-2022.3.8.

**Comment by Brun059** [comment]
great, got it installed, thanks you @scottgerring.  As useless as I am when it comes to installations, I got it working

**Comment by kds69** [comment]
thanks for the [workaround](https://github.com/websylv/homeassistant-meteoswiss/issues/54#issuecomment-1074806964)!
fixed it for me on HA 2022.5.3
