### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by mimaret** [websylv/homeassistant-meteoswiss#56]
Hello,

I use swiss-meteo(V 1.3) in home assistant. It was working very well. Since a few days, I have an error when updating the info. I uninstalled and reinstalled, to no avail.

Thanks in Advance

`Logger: homeassistant.components.sensor
Source: custom_components/meteo-swiss/init.py:77
Integration: Capteur ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 11:40:56 (12 occurrences)
Last logged: 11:41:08
meteo-swiss: Error on device update!

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 737, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
self._data = self._client.get_data()
File "/config/custom_components/meteo-swiss/init.py", line 77, in get_data
return self._client.get_data()
File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 32, in get_data
return {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'`

**Comment by DreadN** [comment]
Hi, Could it be the same problem as #54  and #53 

In #54 a good workaround has been provided by @scottgerring tried it on HA Core in Docker container and it worked.

**Comment by mimaret** [comment]
The problem is solved !

#54 gave me another error and I upgraded to 1.4.

Thanks again

**Comment by DreadN** [comment]
Found it!

**Comment by CamFlyerCH** [comment]
> Found it!

Hmmm, would you please enliight us whete and how?

**Comment by scottgerring** [comment]
> > Found it!
> 
> Hmmm, would you please enliight us whete and how?

There are instructions in the big bolded section I posted in #54
