### ISSUE TITLE
Integration not working for Winterthur

### ISSUE THREAD

**Issue by schneich** [websylv/homeassistant-meteoswiss#59]
### **If you are trying to get this working without console hackery, try this**

I've managed to install it using a HACS manual repository from my own fork. This should work without hacking away at the console and can be done just from the HA web interface:

0. Remove your old meteo-swiss installation from HACS
1. From the HACS integrations screen, click the "..." in the top right corner and select "Custom Repositories"
2. Add `https://github.com/scottgerring/homeassistant-meteoswiss`
3. Click on the meteoswiss integration that appears, and configure normally. When you are prompted for a version, select 1.4. 

It's got the same name as this one in the HACS UI, but you can tell that it's the version that you've published as the authors will include me as well as the original author.

_Originally posted by @scottgerring in https://github.com/websylv/homeassistant-meteoswiss/issues/54#issuecomment-1083611693_

I tried so many dirrent things, but I cannot get this integration running for "8400 Winterthur". All the sonsors are always unavailable/null.
Could someone plase help? Can anybody confirm, that there are temperature, humidity and due point sensors for Winterthur available? If yes, what do I need to do?

**Comment by schneich** [comment]
This is the corresponding log after a reboot:


> 2022-04-10 20:29:37 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration meteo-swiss which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-04-10 20:30:00 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2022-04-10 20:30:00 WARNING (MainThread) [homeassistant.setup] Setup of input_boolean is taking over 10 seconds.
2022-04-10 20:30:00 WARNING (MainThread) [homeassistant.setup] Setup of input_number is taking over 10 seconds.
2022-04-10 20:30:00 WARNING (MainThread) [homeassistant.setup] Setup of counter is taking over 10 seconds.
2022-04-10 20:30:00 WARNING (MainThread) [homeassistant.setup] Setup of timer is taking over 10 seconds.
2022-04-10 20:30:01 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2022-04-10 20:30:02 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform meteo-swiss
Traceback (most recent call last):
File "/config/custom_components/meteo-swiss/sensor.py", line 82, in state
return self._data['condition'][0][dataId]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
if (state := self.state) is None:
File "/config/custom_components/meteo-swiss/sensor.py", line 84, in state
_LOGGER.debug("Unable to return data for : %s"%(self._data['condition'][0][dataId]))
IndexError: list index out of range
2022-04-10 20:30:02 ERROR (MainThread) [homeassistant.components.weather] Error adding entities for domain weather with platform meteo-swiss
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
if (state := self.state) is None:
File "/config/custom_components/meteo-swiss/weather.py", line 95, in state
cond = next(
File "/config/custom_components/meteo-swiss/weather.py", line 99, in <genexpr>
if int(symbolId) in v
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2022-04-10 20:30:02 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up meteo-swiss platform for sensor
Traceback (most recent call last):
File "/config/custom_components/meteo-swiss/sensor.py", line 82, in state
return self._data['condition'][0][dataId]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
if (state := self.state) is None:
File "/config/custom_components/meteo-swiss/sensor.py", line 84, in state
_LOGGER.debug("Unable to return data for : %s"%(self._data['condition'][0][dataId]))
IndexError: list index out of range
2022-04-10 20:30:02 ERROR (MainThread) [homeassistant.components.weather] Error while setting up meteo-swiss platform for weather
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
if (state := self.state) is None:
File "/config/custom_components/meteo-swiss/weather.py", line 95, in state
cond = next(
File "/config/custom_components/meteo-swiss/weather.py", line 99, in <genexpr>
if int(symbolId) in v
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by scottgerring** [comment]
Hi @schneich you can go see [which stations there are on the meteoswiss website](https://www.meteoswiss.admin.ch/home/measurement-values.html?param=messwerte-lufttemperatur-10min&station=CHZ&chart=hour) - if you click "More Info", you can get the abbreviation you need to set up the integration. 


For the postcode I'd use 8404 as it [seems to yield a forecast when you ask for it](https://app-prod-ws.meteoswiss-app.ch/v1/forecast?plz=840400&graph=false&warning=true) - not sure if the difference is important here, haven't dug into how meteoswiss model everything, just tried to fix the breaking API changes.

**Comment by schneich** [comment]
Hi @scottgerring thank you very much for your response. Well, there are some PLZs around Winterthur providing forcast data. I am more interested in current weather conditions, so that I could do some automations in HomeAssistant.
For Winterthur, there seems to be only current temperature, no humidity, no dewpoint. I will try the neigouring villages and see, if I can find something there. Or I just build my own weather station to get the current values just outside our cellar window. :-)

thanks anyway, your help is very much appreciated.
