### ISSUE TITLE
Config flow could not be loaded: undefined

### ISSUE THREAD

**Issue by thor1872** [websylv/homeassistant-meteoswiss#65]
i get this error when trying to add the integration in HA Devices and services.

Logger: aiohttp.server
Source: custom_components/meteo-swiss/config_flow.py:62
Integration: Meteo Swiss ([documentation](https://github.com/websylv/homeassistant-meteoswiss))
First occurred: 6:39:26 PM (1 occurrences)
Last logged: 6:39:26 PM
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Altitude station m. s. mer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 173, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/meteo-swiss/config_flow.py", line 62, in async_step_user
    self._station =await self.hass.async_add_executor_job(self._client.get_closest_station,lat,lon)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 112, in get_closest_station
    self._allStations  = self.__get_all_stations()
  File "/usr/local/lib/python3.9/site-packages/hamsclient/client.py", line 105, in __get_all_stations
    stationData["altitude"] = line["Altitude station m. s. mer"]
  File "/usr/local/lib/python3.9/site-packages/pandas/core/series.py", line 958, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/series.py", line 1069, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'Altitude station m. s. mer'

**Comment by dguinaldo** [comment]
Hi Same issue

**Comment by giulio12** [comment]
Same here

**Comment by martincasagrande** [comment]
And I have the same too

**Comment by nstrelow** [comment]
Same here, this is broken until the right libraries are updated

**Comment by duayfabi** [comment]
the same for me

**Comment by davidschlegel** [comment]
same here

**Comment by tokr1** [comment]
+1

**Comment by chriski12** [comment]
You can resolve this error by editing the hamsclient/client.py file.
This is the path to access this file: /usr/local/lib/python3.10/site-packages/hamsclient/client.py
On line N°105 modify this : stationData["altitude"] = line["Altitude station m. s. mer"] to this : stationData["altitude"] = line["Altitude station m s. mer"] (no point after the "m").
After that you should be able to acces meteo swiss data.

**Comment by martincasagrande** [comment]
Hi
My hamsclient-files are installed in /usr/lib/python3.10/site-packages/hamsclient/client.py. I have edited client.py (no pont after the "m") und saved them. Then I have started the intgartion again, but I still get the error.

  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Altitude station m. s. mer'

I do not understand, why the integration not pickup the client.py. Do I have to clear some cache or to reset anything

**Comment by chriski12** [comment]
Hello Martin,
Did you try to reboot the whole system ? I presume you did. 
I’ve done this modification on a VM and on a RPI and on both times it worked.

**Comment by martincasagrande** [comment]
Yes I have rebooted RPI, twice. I'm wondering I can't change anything in client.py but I still get the same error again.

**Comment by chriski12** [comment]
To change this in client.py, I had to use the ”SSH and Web terminal” add-on and disable the safe mode. 
Then type this command : docker exec -it homeassistant /bin/bash 
And after that : vi /user/local/lib/python3.10/site-packages/hamsclient/client.py to modify the file. Ctrl z z to save and exit. 
After that only reboot and add the integration again

**Comment by chriski12** [comment]
* Shift z z 
My bad

**Comment by thor1872** [comment]
> To change this in client.py, I had to use the ”SSH and Web terminal” add-on and disable the safe mode. Then type this command : docker exec -it homeassistant /bin/bash And after that : vi /user/local/lib/python3.10/site-packages/hamsclient/client.py to modify the file. Ctrl z z to save and exit. After that only reboot and add the integration again

Just so people know it's "usr" and not "user"

So for the beginner like me this is what you need to do.

1: Install SSH & Web Terminal Add-on

2: Disable the protection mode and enable show in sidebar in the setting. Don't forget to add a password in the config tab of this Add-on, if you don't it won't work.

3: Reboot VM or PI (maybe not necessary) but do it anyway. And start SSH & Web Terminal Add-on after reboot if start on boot is disabled.

4: Click on Terminal in the sidebar

5: Type or past this command: docker exec -it homeassistant /bin/bash
(You can use shift + insert to past it in the terminal.)
6: Type or past this command: vi /usr/local/lib/python3.10/site-packages/hamsclient/client.py

7: Edit this line: stationData["altitude"] = line["Altitude station m. s. mer"]
to this:
stationData["altitude"] = line["Altitude station m s. mer"] (no point after the "m").

8: Shift z z to save and close.

9: Reboot the VM or PI

10: Add integration like you normaly do.

And don't forget to stop the Add-on and enable the protection mode of the add-on after using it for security reason.

I have tested this and it work.

Thanks to chriski12 for the help.

Have a nice day all ;)

**Comment by chriski12** [comment]
Thank you thor for your explanations. I was in a hurry when I wrote this answers so it wasn’t as detailed as yours and with a couple errors. 
Glad it helped. 
Have a nice W-E

**Comment by martincasagrande** [comment]
Thank you for the help, it works

**Comment by ElMaquinistaDeTodo** [comment]
worked for me too, thanks Thor1872

**Comment by PierreConstantin** [comment]
docker : command not found  it is install on rpi, the file /usr/local/lib/python3.10/site-packages/hamsclient/client.p does not exist.
hello, how do I install hamsclient. it not trivial for me 
I found it on github. I can download it and then ...... ( I am lost)

**Comment by JogNeuch** [comment]
Sorry, I am quite new in the field. How do you "2: Disable the protection mode" ?

**Comment by Superkikim** [comment]
Tx @Thor1872 . Worked for me. I have sent an email to the add-on author hoping it will fix the hamsclient source given the github repo is not available anymore.

**Comment by capo42** [comment]
yay! Worked. thank you!
Now i can compare the weather with my netatmo.
Lets see!

**Comment by value1-ch** [comment]
> 
> 7: Edit this line: stationData["altitude"] = line["Altitude station m. s. mer"] to this: stationData["altitude"] = line["Altitude station m s. mer"] (no point after the "m").
> 

Thanks @thor1872! This little . made the difference. The integration can be started (no more "500 Internal Server Error" and works fine now!
Thank you for the clear instructions, how to change it.
