### ISSUE TITLE
All 12 entities schow "not available"

### ISSUE THREAD

**Issue by mariusbaumann** [websylv/homeassistant-meteoswiss#66]
Coud install the integration, but all the sensors stay unavailable:
![Bildschirmfoto 2022-08-04 um 14 37 06](https://user-images.githubusercontent.com/9386539/182848675-2bf11623-22b4-436f-8fdb-5b1800299e7b.png)
 
This are the versions of my installation:
Home Assistant 2022.8.0
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220802.0 - latest

This are the HACS versions:
Integrations Version: | 1.26.2
Frontend Version: | 20220714083628

Installed Meteo Swiss Version: 1.4.1

This is the output in the Logs:

Logger: homeassistant.components.sensor
Source: custom_components/meteo-swiss/sensor.py:84
Integration: Sensor (documentation, issues)
First occurred: 14:27:34 (4 occurrences)
Last logged: 14:28:17

Error adding entities for domain sensor with platform meteo-swiss
Error while setting up meteo-swiss platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/meteo-swiss/sensor.py", line 82, in state
    return self._data['condition'][0][dataId]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/meteo-swiss/sensor.py", line 84, in state
    _LOGGER.debug("Unable to return data for : %s"%(self._data['condition'][0][dataId]))
IndexError: list index out of range

![Bildschirmfoto 2022-08-04 um 14 40 44](https://user-images.githubusercontent.com/9386539/182849385-276e252c-2b06-4846-8901-fbab3907a969.png)

**Comment by Lumics** [comment]
Same issue for me

**Comment by Lapeno89** [comment]
same for me too
