### ISSUE TITLE
Add custom component error - KeyError: 'Altitude station m. s. mer'

### ISSUE THREAD

**Issue by kevinpaupe** [websylv/homeassistant-meteoswiss#68]
Hi guys, 

I downloaded the repository on my HACS instance of Home Assistant and I get an error when I try to add the integration.

The logs

`2022-08-08 10:25:13.805 DEBUG (MainThread) [custom_components.meteo-swiss.config_flow] Get closest station for Lon : 7.34614777571551 - Lat : 47.34590734085
2022-08-08 10:25:14.020 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Altitude station m. s. mer'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 249, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/meteo-swiss/config_flow.py", line 62, in async_step_user
    self._station =await self.hass.async_add_executor_job(self._client.get_closest_station,lat,lon)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hamsclient/client.py", line 112, in get_closest_station
    self._allStations  = self.__get_all_stations()
  File "/usr/local/lib/python3.10/site-packages/hamsclient/client.py", line 105, in __get_all_stations
    stationData["altitude"] = line["Altitude station m. s. mer"]
  File "/usr/local/lib/python3.10/site-packages/pandas/core/series.py", line 958, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/series.py", line 1069, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'Altitude station m. s. mer'`

**Comment by kevinpaupe** [comment]
Duplicate, sorry

**Comment by mpanasci** [comment]
Hello,

I've the same error and cannot find a way to fix that :)

Anyone can help ?

**Comment by Quelbazar** [comment]
Please see https://github.com/websylv/homeassistant-meteoswiss/issues/65#issuecomment-1199784205

**Comment by Quelbazar** [comment]
> Hello,
> 
> I've the same error and cannot find a way to fix that :)
> 
> Anyone can help ?

Please read
https://github.com/websylv/homeassistant-meteoswiss/issues/65#issuecomment-1199784205

**Comment by mpanasci** [comment]
> > Hello,
> > I've the same error and cannot find a way to fix that :)
> > Anyone can help ?
> 
> Please read [#65 (comment)](https://github.com/websylv/homeassistant-meteoswiss/issues/65#issuecomment-1199784205)

Thank you very much, it works fine !!!
