### ISSUE TITLE
installation does not work

### ISSUE THREAD

**Issue by danielgut8330** [websylv/homeassistant-meteoswiss#69]
Hello, I'm still a beginner with Home Assistant, so the maybe a bit strange question: What do I have to do if I get the following error message when installing Meteo Swiss: The configuration flow could not be loaded: undefined

if someone can help me I'll be very grateful

**Comment by drdadr** [comment]
Same here!

**Comment by thierrystadler** [comment]
I have the same problem

**Comment by Eponas07** [comment]
I have the same problem

**Comment by thierrystadler** [comment]
Work around
Install version 1.3, this version seems to still works

**Comment by salvisbh** [comment]
1.3 does not work too

**Comment by Eponas07** [comment]
Unfortunately version 1.3 does not work for me either

**Comment by PierreConstantin** [comment]
hello,
I have the same problem installing meteoswiss in ha.
doing with HACS, integration, download repository,meteoswiss, download, 
developper tools, restart
then setting integration, add integration meteoswiss
sfter a while error Config flow not be loaded: undefined
note: hacs and file editor also crash, I have to restart them

I tr to uninstall in hacs, reboot , reinstall but always the same problem

**Comment by Lex1** [comment]
Same here. After trying to add new integration "Meteo Swiss" (in Settings:Integrations), I get a popup window with "Config flow could not be loaded: undefined"

Full log:

2022-09-05 00:33:38.310 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration meteo-swiss which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-09-05 00:34:14.295 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
return self._engine.get_loc(casted_key)
File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Altitude station m. s. mer'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
return await super().post(request)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
result = await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
result = await self._flow_mgr.async_init(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
flow, result = await task
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 249, in _async_init
result = await self._async_handle_step(flow, flow.init_step, data, init_done)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/meteo-swiss/config_flow.py", line 62, in async_step_user
self._station =await self.hass.async_add_executor_job(self._client.get_closest_station,lat,lon)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/hamsclient/client.py", line 112, in get_closest_station
self._allStations = self.__get_all_stations()
File "/usr/local/lib/python3.10/site-packages/hamsclient/client.py", line 105, in __get_all_stations
stationData["altitude"] = line["Altitude station m. s. mer"]
File "/usr/local/lib/python3.10/site-packages/pandas/core/series.py", line 958, in __getitem__
return self._get_value(key)
File "/usr/local/lib/python3.10/site-packages/pandas/core/series.py", line 1069, in _get_value
loc = self.index.get_loc(label)
File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
raise KeyError(key) from err
KeyError: 'Altitude station m. s. mer'

**Comment by subw0ofer** [comment]
I had the same error when installing 1.4.1 ("Config flow could not be loaded: undefined"). I managed it to run the Integration with following workaround:

- I removed version 1.4.1
- I installed version 1.3 with HACS - then i was able to add the Integration
- Afterwards I updated the Integration in HACS to 1.4.1 again
- Now its working for me.

**Comment by Lex1** [comment]
> I had the same error when installing 1.4.1 ("Config flow could not be loaded: undefined"). I managed it to run the Integration with following workaround:
> 
> * I removed version 1.4.1
> * I installed version 1.3 with HACS - then i was able to add the Integration
> * Afterwards I updated the Integration in HACS to 1.4.1 again
> * Now its working for me.

Thanks, this also worked for me

**Comment by PierreConstantin** [comment]
sorry not easy to follow you. how to you install version 1.3 with Hacs. I found it on github, download on custom_componant but in add integration I dont have meteoswiss

**Comment by PierreConstantin** [comment]
thanks. work for me. however after install of v 1.3 it need a reboot. with a restart integration meteoswiss is not there

**Comment by nasgulch** [comment]
Same error here. Just unusable.
Too bad.

**Comment by Lex1** [comment]
> thanks. work for me. however after install of v 1.3 it need a reboot. with a restart integration meteoswiss is not there

After cleaning the browser cache completely, I could see the integration (seems to be a general problem of HA/HACS)

**Comment by stefanoklett** [comment]
Similar problem, when installing meteoswiss I get:
500 Internal Server Error Server got itself in trouble

regards

**Comment by TasukiNekoi** [comment]
> Similar problem, when installing meteoswiss I get: 500 Internal Server Error Server got itself in trouble
> 
> regards

I can confirm that I got the same issue

**Comment by GitNeusch** [comment]
#    I had the same error when installing 1.4.1 ("Le flux de configuration n'a pas pu être chargé: 500 Internal Server Error Server #got itself in trouble). I managed it to run the Integration with following workaround:
#
#        I removed version 1.4.1 (+ redémarrer HA)
#       I installed version 1.3 with HACS - then i was able to add the Integration
#       Afterwards I updated the Integration in HACS to 1.4.1 again
#        Now its working for me.

 # Thanks, this also worked for me
Merci, cela a aussi fonctionné pour moi

**Comment by GitNeusch** [comment]
I had the same error when installing 1.4.1 ("Le flux de configuration n'a pas pu être chargé: 500 Internal Server Error Server #got itself in trouble). I managed it to run the Integration with following workaround:
I removed version 1.4.1 (+ redémarrer HA)
I installed version 1.3 with HACS - then i was able to add the Integration
Afterwards I updated the Integration in HACS to 1.4.1 again
Now its working for me.
Thanks, this also worked for me

Merci, cela a aussi fonctionné pour moi

**Comment by Rudd-O** [comment]
I've forked it:

https://github.com/Rudd-O/homeassistant-meteoswiss

Mine works.

**Comment by TasukiNekoi** [comment]
> I've forked it:
> 
> https://github.com/Rudd-O/homeassistant-meteoswiss
> 
> Mine works.

Great, thank you!

**Comment by perdicaro** [comment]
> L'ho biforcato:
> 
> https://github.com/Rudd-O/homeassistant-meteoswiss
> 
> La mia funziona.

I tried to add https://github.com/Rudd-O/homeassistant-meteoswiss/pulls as repository but it doesn't work, how do I fix the instalation problem?

**Comment by Rudd-O** [comment]
[https://github.com/Rudd-O/homeassistant-meteoswiss](https://github.com/Rudd-O/homeassistant-meteoswiss/pulls) is what you must add as a repository.

Now install the Swiss Meteo (forked) integration.  Ensure you removed the existing one if any.
