### ISSUE TITLE
Error adding entities for domain weather with platform meteo-swiss

### ISSUE THREAD

**Issue by steuerzentrale** [websylv/homeassistant-meteoswiss#79]
Hi there

I installed the forked Meteo Swiss and then configured the Meteo swiss integration. Before doing that I made sure that I deleted the old meteo-swiss integration and its entities too.

<img width="559" alt="Bildschirm­foto 2023-01-22 um 11 17 54" src="https://user-images.githubusercontent.com/75168550/213910757-b5f138aa-780a-4964-9b5f-b9f144aa0f8a.png">

the integration found 12 entities:
<img width="512" alt="Bildschirm­foto 2023-01-22 um 11 18 27" src="https://user-images.githubusercontent.com/75168550/213910818-d4fa5681-c1db-44

unfortunately the entites dont seem to be working:
<img width="1055" alt="Bildschirm­foto 2023-01-22 um 11 18 35" src="https://user-images.githubusercontent.com/75168550/213910821-fea360fb-7009-4f9f-9717-696fab312b35.png">
0d-9ab5-f0f0bc4db7e8.png">

I got the following error in the system log:

Logger: homeassistant.components.sensor
Source: custom_components/meteo-swiss/sensor.py:58
Integration: Sensor (documentation, issues)
First occurred: 11:13:58 (2 occurrences)
Last logged: 11:13:58

Error adding entities for domain sensor with platform meteo-swiss
Error while setting up meteo-swiss platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/meteo-swiss/sensor.py", line 56, in state
    return self._data['condition'][0][dataId]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 804, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/meteo-swiss/sensor.py", line 58, in state
    _LOGGER.debug("Unable to return data for : %s"%(self._data['condition'][0][dataId]))
IndexError: list index out of range

any help is greatly appreciated
<img width="247" alt="Bildschirm­foto 2023-01-22 um 11 21 00" src="https://user-images.githubusercontent.com/75168550/213910881-ccb4137c-342e-4ad5-9b72-1cd485b801ac.png">

all the best

Andrew

**Comment by phil-schneider** [comment]
Which working Fork did you install?

**Comment by steuerzentrale** [comment]
the one from Rudd-O as per the instruction I added the custom HACS repository (https://github.com/Rudd-O/homeassistant-meteoswiss)

**Comment by itspt1** [comment]
I have the same issue. My logs show the same as well.
Using the fork from @rudd-o https://github.com/Rudd-O/homeassistant-meteoswiss.

**Comment by Rudd-O** [comment]
Very strange!  Can you share your config?  I need to reproduce.  For now I will push a minor change to aid debuggability.  Update the integration and restart HASS in ~20 minutes.

**Comment by Rudd-O** [comment]
I've pushed `8a8832a..a28f33d` which won't address the issue but will give us more information on how to proceed.  Thank you.

**Comment by Rudd-O** [comment]
I've pushed an update which addresses the issue.

You may have to re-setup the integration.

**Comment by Rudd-O** [comment]
I've pushed another update that lets you know (in the Repairs section of Home Assistant) if the station you are using has stopped providing data.  This should address some issues people were having.  This in fact addresses the issue of index error out of range!
