### ISSUE TITLE
ValueError: could not convert string to float: '-'

### ISSUE THREAD

**Issue by maxkueng** [websylv/homeassistant-meteoswiss#8]
Hello. I tried to use the integration with the following config and, after restarting HA, I got the following error in the logs and the sensor doesn't show up. I'm using Home Assistant 0.109.0.

I don't know a lot about Python and i"m pretty new to HA, but it looks like the station auto-selected for my postcode returned `'-'` for humidity instead of a number and that was unexpected by the code?

Config:
```
weather:
  - platform: meteo-swiss
    name: "MeteoSwiss"
    postcode: 8038
```

Error while setting up meteo-swiss platform for weather

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 445, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 133, in state_attributes
    humidity = self.humidity
  File "/config/custom_components/meteo-swiss/weather.py", line 207, in humidity
    return float(self._condition[0]['ure200s0'])
ValueError: could not convert string to float: '-'
```

Thank you <3

**Comment by websylv** [comment]
i will handle the missing data properly same time as fixing the sync IO

**Comment by dalwhin** [comment]
I have the same error as maxkueng. I returned to version 0.5.1 and everything is working again.

Maybe this helps as a temporary work around.

**Comment by websylv** [comment]
it will be fix in the next release 
probably next week

**Comment by websylv** [comment]
i published a new release 
please read the doc ! you need to do manual action before and after the upgrade

**Comment by Medi64** [comment]
Great job! Integration runs on my Raspberry Pi. Thank you very much for all your efforts on this.

**Comment by dalwhin** [comment]
Thanks for the update. Everything is working smooth without any error in the log file :-)

**Comment by maxkueng** [comment]
Can confirm. Works perfectly. Thanks!
