### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Guezli** [websylv/homeassistant-meteoswiss#83]
Wenn ich die Integration installieren will, erhalte ich den nachfolgenden Fehler:

![Uploading D8C8396A-69F2-408B-92B5-A8BD8704B3E7.jpeg…]()

Hier ist die Meldung aus dem Logbuch:

`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: aiohttp.server
Source: custom_components/meteo-swiss/config_flow.py:62 
Integration: Meteo Swiss (documentation) 
First occurred: 17:00:24 (2 occurrences) 
Last logged: 17:01:21

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Altitude station m. s. mer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 831, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 859, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/meteo-swiss/config_flow.py", line 62, in async_step_user
    self._station =await self.hass.async_add_executor_job(self._client.get_closest_station,lat,lon)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hamsclient/client.py", line 112, in get_closest_station
    self._allStations  = self.__get_all_stations()
  File "/usr/local/lib/python3.10/site-packages/hamsclient/client.py", line 105, in __get_all_stations
    stationData["altitude"] = line["Altitude station m. s. mer"]
  File "/usr/local/lib/python3.10/site-packages/pandas/core/series.py", line 958, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/series.py", line 1069, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'Altitude station m. s. mer'
`

**Comment by CroHammeR** [comment]
bei mir das gleiche...

**Comment by Guezli** [comment]
Ich fand hier im Forum die [Lösung](https://github.com/websylv/homeassistant-meteoswiss/issues/65#issuecomment-1199784205). Jetzt funktioniert es.

**Comment by value1-ch** [comment]
> Ich fand hier im Forum die [Lösung](https://github.com/websylv/homeassistant-meteoswiss/issues/65#issuecomment-1199784205). Jetzt funktioniert es.

Danke @Guezli für den Link. Funktioniert nun tadellos ohne den "500 internal server error"!
