### ISSUE TITLE
not work with home assistent 2023.06

### ISSUE THREAD

**Issue by addich** [websylv/homeassistant-meteoswiss#85]
workaround : rename the folder 'meteo-swiss' to 'meteoswiss' under custom_components folder, restart HA...

**Comment by jicka** [comment]
Same here. I cannot add the integration after installation. Renaming the folder did not help. Here is the issue in the logs:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Altitude station m. s. mer'
```

**Comment by 0815pascal** [comment]
+1

**Comment by Mimosa-oceanis** [comment]
I got the same issue as @jicka and renaming the folder didn't help either.

**Comment by conan747** [comment]
+1
